version: '3'
services:
  db:
    image: 'postgres:13-alpine'
    container_name: assignment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: assignment
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
